### ISSUE TITLE
Apple Intelligence bricked iOS updates on iPhone SE 2022

### ISSUE THREAD

**Issue by ThunderboltCommunicationsCorp** [leminlimez/Nugget#133]
I used Nugget to enable Apple intelligence, spoofed my iPhone SE and all that and then I noticed in settings saying camera not recognized. I ignored it since the camera seemed to work fine but then noticed that when iOS 18.2 beta 1 and later came out, I wanted to download it and it either wouldn't appear as an option, or it would just infinitely say checking for updates. (Before you ask, yes I did remove the spoofing and all the tweaks as well as an attempt to fix this, it doesn't do anything, same results). Please let me know if there's a way to fix this mess. Thank you!

**Comment by Morugogo** [comment]
Sorry in advance for my bad English, I have an iPhone SE 2020, and Apple Intelligence blocks updates from what I understand, for me to update for example to beta 18.2 beta 2, I have to remove Apple Intelligence, or reset my mobile gestalt , and there go to the update section and the new updates will appear without any problem, to verify that everything is correct, you can go to Apple ID of the device and the name of the device you have will appear, iPhone 16 no longer has to appear pro or the device you chose to "fake" the apple servers, if not the name of the original device, from there you can activate apple intelligence from the new version without problems, what I would believe is that the exploit blocks the updates so that they do not there are problems, or the apple servers do not find a version for an "iphone 16 pro with iphone se components".

**Comment by leminlimez** [comment]
click the "reset mobile gestalt" button
