### ISSUE TITLE
will there ever be support for 18.2 22c152 and higher?

### ISSUE THREAD

**Issue by dolbaeb486** [leminlimez/Nugget#309]
will there ever be support for 18.2 22c152 and higher?

**Comment by moon-cacke** [comment]
Very unlikely... only if apple decide to relax sparserestore for mobilegestalt

**Comment by baobaoit** [comment]
You already have the answer at the README.md

https://github.com/leminlimez/Nugget/blob/af6abe60051aea30bca8cd612d8e9c21b39dff21/README.md?plain=1#L6

>  **Mobilegestalt and AI Enabler tweaks are not supported on iOS 18.2+.** It will never be supported, do not make issues asking for when it is supported. 

And in release note already remind it again

> NOTE: Mobilegestalt tweaks will never support iOS 18.2+. Do not make an issue about it.

And you still ask this question? If Apple allow it, then the dev will update, you don’t need to ask, it belongs to Apple decision, the dev can’t do anythings if the bug had fixed by Apple.
